# Generated by Django 4.1.7 on 2023-03-12 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="project name"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(upload_to="images", verbose_name="project logo"),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=1000, verbose_name="project description"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(max_length=100, verbose_name="project purpose"),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        default="2023-03-13",
                        verbose_name="project deadline",
                    ),
                ),
                (
                    "vote_deadline",
                    models.DateField(verbose_name="project vote deadline"),
                ),
                (
                    "phase",
                    models.SmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="project phase",
                    ),
                ),
                (
                    "invalid",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="invalid project"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        to="users.user", verbose_name="project users"
                    ),
                ),
            ],
        ),
    ]
