# Generated by Django 4.1.7 on 2023-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(
                blank=True, default="2023-03-18", verbose_name="project deadline"
            ),
        ),
    ]
