# Generated by Django 4.1.7 on 2023-03-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("summary", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                ("purpose", models.CharField(max_length=100)),
                ("project_deadline", models.DateField()),
                ("contact", models.CharField(max_length=100)),
                ("vote_deadline", models.DateField()),
            ],
        ),
    ]
