# Generated by Django 4.1.7 on 2023-03-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="project name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=1000, verbose_name="project description"
                    ),
                ),
                (
                    "projects",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="Reference project",
                    ),
                ),
                (
                    "users",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                        verbose_name="proposal users",
                    ),
                ),
            ],
        ),
    ]
