# Generated by Django 4.1.7 on 2023-03-12 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(
                        max_length=42,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(42)],
                        verbose_name="user wallet address",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email address"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(upload_to="images", verbose_name="user icon"),
                ),
            ],
        ),
    ]
