# Generated by Django 4.1.7 on 2023-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="icon",
        ),
        migrations.AddField(
            model_name="user",
            name="tokenId",
            field=models.IntegerField(default=0, verbose_name="user token id"),
            preserve_default=False,
        ),
    ]
